// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAycZWL6UuMO1MvV6gB1IeX1C5ywVPXZfM',
    appId: '1:592513833457:web:4d0e9cf7bf9d0c6cbccc50',
    messagingSenderId: '592513833457',
    projectId: 'sqltest-1ae9e',
    authDomain: 'sqltest-1ae9e.firebaseapp.com',
    storageBucket: 'sqltest-1ae9e.appspot.com',
    databaseURL: 'https://console.firebase.google.com/project/sqltest-1ae9e/database/sqltest-1ae9e-default-rtdb/data/~2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVK_3ECyXjX6j1tiwH6M5-eqQGy_E1nw',
    appId: '1:592513833457:android:64113a2de805b23abccc50',
    messagingSenderId: '592513833457',
    projectId: 'sqltest-1ae9e',
    storageBucket: 'sqltest-1ae9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7htMd8pWCglAAwduF-yMAanJpxHNqjo',
    appId: '1:592513833457:ios:415370e2da3d70c2bccc50',
    messagingSenderId: '592513833457',
    projectId: 'sqltest-1ae9e',
    storageBucket: 'sqltest-1ae9e.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7htMd8pWCglAAwduF-yMAanJpxHNqjo',
    appId: '1:592513833457:ios:28f10ba80a1af7fdbccc50',
    messagingSenderId: '592513833457',
    projectId: 'sqltest-1ae9e',
    storageBucket: 'sqltest-1ae9e.appspot.com',
    iosBundleId: 'com.example.testProject.RunnerTests',
  );
}
